version: '3.8'
services:
  db:
    container_name: pg_container
    image: postgres
    volumes:
      - ./postgres_db_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: interop
      POSTGRES_PASSWORD: interop
      POSTGRES_DB: interop
    ports:
      - "8001:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: dusanp96@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_SESSION_PROTECTION: "None"
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
      PGADMIN_CONFIG_SESSION_COOKIE_SAMESITE: "None"
    ports:
      - "5050:80"
    volumes:
     - ./servers.json:/pgadmin4/servers.json # preconfigured servers/connections
     - ./pgpass:/pgpass # passwords for the connections in this file
    depends_on:
     - "db"